### ISSUE TITLE
Doesn't have required modules.

### ISSUE THREAD

**Issue by NiklavsD** [tedztar/mcstatusbotROOT#16]
```
root@dexp:/home/discord# node mcbot.js
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'request'
Require stack:
- /home/discord/mcbot.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/discord/mcbot.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/discord/mcbot.js' ]
}
root@dexp:/home/discord#

```

I installed everything: npm, node.js, discord.js

**Comment by Huskydog9988** [comment]
follow the directions, it tells you how to install dependencies.

**Comment by NiklavsD** [comment]
Does it work for other game server too?

**Comment by Huskydog9988** [comment]
No because of the API server the bot uses it can only read the data of mc java servers.

**Comment by tedztar** [comment]
Closing as user needs to install dependencies.
